Attempt to use delegating Spliterators on Android 7.0 (Nougat)+.
Prior to this change, delegating Spliterators were only used on
limited platforms (not including Android). This can be demonstrated
with the following test which now passes but would previously have
failed (expected:<[Delegating]Spliterator> but was:<[Entry]Spliterator>):

    @Test
    public void testAndroidN_delegatingSpliterator() {
      Spliterator spliterator = Spliterators.spliterator(
          new HashMap<>().entrySet());
      assertEquals("DelegatingSpliterator",
          spliterator.getClass().getSimpleName());
    }

I did not perform any other verification steps so this change may
contain errors. Specifically, I couldn't figure out how to run
streamsupport's test suite so I didn't run them: the gradle rule
("test") failed to compile because it couldn't find the Maps2 class
(probably a missing dependency config somewhere?) and "mvn test"
claimed that there were zero tests to run.

To clarify that additional platforms now offer delegating
Spliterators, renamed JRE_DELEGATION_ENABLED and friends to
DELEGATION_ENABLED. The corresponding system property's name remains
".jre.delegation.enabled" for the following reasons:

   (a) to maintain backwards compatibility,
   (b) because system properties make less sense on Android (there is
       no command line to set them from, so they'd need to be set from
       code before Spliterators.<clinit> runs)

To make the code more robust, refactored logic for static initialization
logic in Spliterators.java into static helper methods. The advantage is
that those methods can be called in arbitrary order, including during
initialization of other static fields. If methods such as
isStreamEnabled() were reading those static fields directly while
computing the value for another static field, the correct initialization
order would depend on the order those static fields appear in the .java
file, which would be fragile and could easily break.